/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.Layout;

import controllers.AccountBUS;
import controllers.TransportationTypeBUS;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import models.Account;
import models.Role;
import models.TransportationType;
import org.bson.types.ObjectId;

/**
 *
 * @author Son
 */
public class AccountGUI extends javax.swing.JPanel {

    private TransportationType selectedTransportationType;
    private Account account;
    private AccountBUS accountBUS;
    private Account selectedAccount;
    private JFrame parentFrame=null;
    /**
     * Creates new form OwnerGUI
     */
    public AccountGUI(Account account) {
        initComponents();
        accountBUS = new AccountBUS();
        this.account = account;
        SwingUtilities.invokeLater(() -> {
            parentFrame = (MainLayout) SwingUtilities.getWindowAncestor(this);
        });
        System.out.println(parentFrame==null);
        getAccountsData();
    }
    
    public void getAccountsData(){
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        List<Account> accounts = accountBUS.getAll();
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        int i=0;
        for(Account account:accounts){
            String Status = account.isActived()?"Kích hoạt":"Chưa kích hoạt";
            Object[] row = new Object[]{++i,account.getUsername(),dateFormat.format(account.getCreatedDate()),Status,account.getId()};
            model.addRow(row);
        }
    }
    public void getAccountDetail(Account account){
        if(account!=null){
            nameTxt.setText(account.getName());
            emailTxt.setText(account.getEmail());
            if(account.getGender().equals("Nam"))
                maleOption.setSelected(true);
            else 
                femaleOption.setSelected(true);
            phoneTxt.setText(account.getPhone());
            ownerRole.setSelectedIndex(account.getRole().getOwnerManager());
            transportationRole.setSelectedIndex(account.getRole().getTransportationManager());
            transportationTypeRole.setSelectedIndex(account.getRole().getTransportationTypeManager());
            AccountRole.setSelectedIndex(account.getRole().getAccountManager());
        }
    }
    public void refresh(){
        nameTxt.setText("");
        emailTxt.setText("");
        genderOption.clearSelection();
        phoneTxt.setText("");
        ownerRole.setSelectedIndex(0);
        transportationRole.setSelectedIndex(0);
        transportationTypeRole.setSelectedIndex(0);
        AccountRole.setSelectedIndex(0);
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderOption = new javax.swing.ButtonGroup();
        contentPanel2 = new javax.swing.JPanel();
        roundPanel3 = new view.custom.RoundPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblCategoryIDConfig = new javax.swing.JLabel();
        nameTxt = new view.custom.textField();
        lblCategoryIDConfig1 = new javax.swing.JLabel();
        emailTxt = new view.custom.textField();
        lblCategoryIDConfig2 = new javax.swing.JLabel();
        maleOption = new javax.swing.JRadioButton();
        femaleOption = new javax.swing.JRadioButton();
        lblCategoryIDConfig3 = new javax.swing.JLabel();
        lblCategoryIDConfig4 = new javax.swing.JLabel();
        lblCategoryIDConfig5 = new javax.swing.JLabel();
        lblCategoryIDConfig6 = new javax.swing.JLabel();
        lblCategoryIDConfig7 = new javax.swing.JLabel();
        ownerRole = new javax.swing.JComboBox<>();
        lblCategoryIDConfig8 = new javax.swing.JLabel();
        lblCategoryIDConfig9 = new javax.swing.JLabel();
        phoneTxt = new view.custom.textField();
        lblCategoryIDConfig10 = new javax.swing.JLabel();
        birthdateField = new de.wannawork.jcalendar.JCalendarComboBox();
        button6 = new view.custom.Button();
        button5 = new view.custom.Button();
        transportationRole = new javax.swing.JComboBox<>();
        transportationTypeRole = new javax.swing.JComboBox<>();
        AccountRole = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        activeBtn = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1266, 550));

        contentPanel2.setBackground(new java.awt.Color(51, 51, 51));
        contentPanel2.setPreferredSize(new java.awt.Dimension(1266, 550));
        contentPanel2.setVerifyInputWhenFocusTarget(false);

        roundPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "username", "Ngày khởi tạo", "Trạng thái", "id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setPreferredWidth(10);
            table.getColumnModel().getColumn(4).setMinWidth(0);
            table.getColumnModel().getColumn(4).setPreferredWidth(0);
            table.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        javax.swing.GroupLayout roundPanel3Layout = new javax.swing.GroupLayout(roundPanel3);
        roundPanel3.setLayout(roundPanel3Layout);
        roundPanel3Layout.setHorizontalGroup(
            roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundPanel3Layout.setVerticalGroup(
            roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblCategoryIDConfig.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblCategoryIDConfig.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoryIDConfig.setText("Chủ sở hữu:");

        nameTxt.setBackground(new java.awt.Color(51, 51, 51));
        nameTxt.setForeground(new java.awt.Color(255, 255, 255));
        nameTxt.setFocusable(false);
        nameTxt.setLabelText("Họ và tên");

        lblCategoryIDConfig1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblCategoryIDConfig1.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoryIDConfig1.setText("Email:");

        emailTxt.setBackground(new java.awt.Color(51, 51, 51));
        emailTxt.setForeground(new java.awt.Color(255, 255, 255));
        emailTxt.setFocusable(false);
        emailTxt.setLabelText("Email");

        lblCategoryIDConfig2.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblCategoryIDConfig2.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoryIDConfig2.setText("Họ tên:");

        genderOption.add(maleOption);
        maleOption.setForeground(new java.awt.Color(255, 255, 255));
        maleOption.setText("Nam");
        maleOption.setEnabled(false);

        genderOption.add(femaleOption);
        femaleOption.setForeground(new java.awt.Color(255, 255, 255));
        femaleOption.setText("Nữ");
        femaleOption.setEnabled(false);

        lblCategoryIDConfig3.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblCategoryIDConfig3.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoryIDConfig3.setText("Giới tính:");

        lblCategoryIDConfig4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCategoryIDConfig4.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoryIDConfig4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCategoryIDConfig4.setText("Thông tin cơ bản");

        lblCategoryIDConfig5.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblCategoryIDConfig5.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoryIDConfig5.setText("Xe:");

        lblCategoryIDConfig6.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblCategoryIDConfig6.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoryIDConfig6.setText("Dòng xe:");

        lblCategoryIDConfig7.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblCategoryIDConfig7.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoryIDConfig7.setText("Phân quyền:");

        ownerRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vô hiệu", "Chỉ xem", "Chỉnh sửa" }));

        lblCategoryIDConfig8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCategoryIDConfig8.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoryIDConfig8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCategoryIDConfig8.setText("Phân quyền");

        lblCategoryIDConfig9.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblCategoryIDConfig9.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoryIDConfig9.setText("Số điện thoại:");

        phoneTxt.setBackground(new java.awt.Color(51, 51, 51));
        phoneTxt.setForeground(new java.awt.Color(255, 255, 255));
        phoneTxt.setFocusable(false);
        phoneTxt.setLabelText("Số điện thoại");

        lblCategoryIDConfig10.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblCategoryIDConfig10.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoryIDConfig10.setText("Ngày sinh:");

        birthdateField.setEnabled(false);
        birthdateField.setFocusable(false);
        birthdateField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        button6.setBackground(new java.awt.Color(204, 204, 255));
        button6.setBorder(null);
        button6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/refresh.png"))); // NOI18N
        button6.setText("Làm mới");
        button6.setToolTipText("");
        button6.setBorderColor(new java.awt.Color(0, 0, 0));
        button6.setColor(new java.awt.Color(204, 204, 255));
        button6.setColorClick(new java.awt.Color(240, 235, 235));
        button6.setColorOver(new java.awt.Color(255, 255, 255));
        button6.setFocusPainted(false);
        button6.setRadius(20);
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        button5.setBackground(new java.awt.Color(204, 204, 255));
        button5.setBorder(null);
        button5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/wrench.png"))); // NOI18N
        button5.setText("Cập nhật");
        button5.setToolTipText("");
        button5.setBorderColor(new java.awt.Color(0, 0, 0));
        button5.setColor(new java.awt.Color(204, 204, 255));
        button5.setColorClick(new java.awt.Color(240, 235, 235));
        button5.setColorOver(new java.awt.Color(255, 255, 255));
        button5.setFocusPainted(false);
        button5.setRadius(20);
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        transportationRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vô hiệu", "Chỉ xem", "Chỉnh sửa" }));

        transportationTypeRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vô hiệu", "Chỉ xem", "Chỉnh sửa" }));

        AccountRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vô hiệu", "Chỉ xem", "Chỉnh sửa" }));

        activeBtn.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        activeBtn.setForeground(new java.awt.Color(255, 255, 255));
        activeBtn.setText("Kích hoạt");
        activeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        activeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                activeBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout contentPanel2Layout = new javax.swing.GroupLayout(contentPanel2);
        contentPanel2.setLayout(contentPanel2Layout);
        contentPanel2Layout.setHorizontalGroup(
            contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(contentPanel2Layout.createSequentialGroup()
                        .addGroup(contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCategoryIDConfig1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoryIDConfig2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(contentPanel2Layout.createSequentialGroup()
                        .addGroup(contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCategoryIDConfig9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoryIDConfig3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(contentPanel2Layout.createSequentialGroup()
                                .addComponent(maleOption)
                                .addGap(18, 18, 18)
                                .addComponent(femaleOption)
                                .addGap(18, 18, 18)
                                .addComponent(lblCategoryIDConfig10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(birthdateField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contentPanel2Layout.createSequentialGroup()
                                .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(activeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblCategoryIDConfig4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCategoryIDConfig8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanel2Layout.createSequentialGroup()
                        .addGroup(contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(contentPanel2Layout.createSequentialGroup()
                                    .addComponent(lblCategoryIDConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ownerRole, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(contentPanel2Layout.createSequentialGroup()
                                    .addComponent(lblCategoryIDConfig5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(transportationRole, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentPanel2Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(contentPanel2Layout.createSequentialGroup()
                                        .addComponent(lblCategoryIDConfig7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AccountRole, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(contentPanel2Layout.createSequentialGroup()
                                        .addComponent(lblCategoryIDConfig6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(transportationTypeRole, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(contentPanel2Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        contentPanel2Layout.setVerticalGroup(
            contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contentPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblCategoryIDConfig4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoryIDConfig2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCategoryIDConfig1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(maleOption)
                                .addComponent(femaleOption)
                                .addComponent(lblCategoryIDConfig3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCategoryIDConfig10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(birthdateField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoryIDConfig9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(activeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCategoryIDConfig8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCategoryIDConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoryIDConfig6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ownerRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transportationTypeRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCategoryIDConfig5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoryIDConfig7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transportationRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AccountRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addGroup(contentPanel2Layout.createSequentialGroup()
                        .addGap(0, 154, Short.MAX_VALUE)
                        .addComponent(roundPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1190, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        if (evt.getClickCount() == 2) {
            JTable target = (JTable) evt.getSource();
            int row = target.getSelectedRow();
            ObjectId id =(ObjectId) table.getValueAt(row, 4);
            selectedAccount = accountBUS.getById(id);
            if(selectedAccount==null){
                JOptionPane.showMessageDialog(contentPanel2, "Có lỗi xảy ra!! tiến hành tải lại trang...");
                refresh();
                getAccountsData();
                return;
            }
            getAccountDetail(selectedAccount);
        }
    }//GEN-LAST:event_tableMouseClicked

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
//        if(selectedOwner!=null)
//        setOwnerDetail(selectedOwner);
//        else
//        JOptionPane.showMessageDialog(contentPanel2, "Vui lòng chọn một đối tượng để thao táo");
    }//GEN-LAST:event_button6ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        if(accountBUS.getById(account.getId()).getRole().getAccountManager()!=2){
            JOptionPane.showMessageDialog(contentPanel2, "Bạn không có quyền thao tác");
            return;
        }
        if(selectedAccount==null){
            JOptionPane.showMessageDialog(contentPanel2, "Vui lòng chọn một đối tượng thể thao tác");
            return;
        }
        int ownerRole = this.ownerRole.getSelectedIndex();
        int transportationRole = this.transportationRole.getSelectedIndex();
        int transportationTypeRole = this.transportationTypeRole.getSelectedIndex();
        int accountRole = AccountRole.getSelectedIndex();
        Role newRole = new Role(ownerRole, transportationRole, transportationTypeRole, accountRole);
        selectedAccount.setRole(newRole);
        if(accountBUS.update(selectedAccount)){
            JOptionPane.showMessageDialog(contentPanel2, "Cập nhật thành công!");
            refresh();
            selectedAccount=null;
            getAccountsData();
        }else {
            JOptionPane.showMessageDialog(contentPanel2, "Có lỗi xảy ra");
        }
        
    }//GEN-LAST:event_button5ActionPerformed

    private void activeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activeBtnMouseClicked
        if(accountBUS.getById(account.getId()).getRole().getAccountManager()!=2){
            JOptionPane.showMessageDialog(contentPanel2, "Bạn không có quyền thao tác");
            return;
        }
        if(selectedAccount!=null){
            selectedAccount.setActived(true);
            if(accountBUS.update(selectedAccount)){
                JOptionPane.showMessageDialog(contentPanel2, "Kích hoạt thành công");
                activeBtn.setText("Đã kích hoạt");
                activeBtn.setEnabled(false);
                getAccountsData();
            }
        }else {
            JOptionPane.showMessageDialog(contentPanel2, "Vui lòng chọn đối tượng thao tác");
        }
    }//GEN-LAST:event_activeBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AccountRole;
    private javax.swing.JLabel activeBtn;
    private de.wannawork.jcalendar.JCalendarComboBox birthdateField;
    private view.custom.Button button5;
    private view.custom.Button button6;
    private javax.swing.JPanel contentPanel2;
    private view.custom.textField emailTxt;
    private javax.swing.JRadioButton femaleOption;
    private javax.swing.ButtonGroup genderOption;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCategoryIDConfig;
    private javax.swing.JLabel lblCategoryIDConfig1;
    private javax.swing.JLabel lblCategoryIDConfig10;
    private javax.swing.JLabel lblCategoryIDConfig2;
    private javax.swing.JLabel lblCategoryIDConfig3;
    private javax.swing.JLabel lblCategoryIDConfig4;
    private javax.swing.JLabel lblCategoryIDConfig5;
    private javax.swing.JLabel lblCategoryIDConfig6;
    private javax.swing.JLabel lblCategoryIDConfig7;
    private javax.swing.JLabel lblCategoryIDConfig8;
    private javax.swing.JLabel lblCategoryIDConfig9;
    private javax.swing.JRadioButton maleOption;
    private view.custom.textField nameTxt;
    private javax.swing.JComboBox<String> ownerRole;
    private view.custom.textField phoneTxt;
    private view.custom.RoundPanel roundPanel3;
    private javax.swing.JTable table;
    private javax.swing.JComboBox<String> transportationRole;
    private javax.swing.JComboBox<String> transportationTypeRole;
    // End of variables declaration//GEN-END:variables
}
