/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.Layout;

import controllers.AccountBUS;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import models.Account;

/**
 *
 * @author Son
 */
public class LoginForm extends javax.swing.JPanel {
    private final AccountBUS accountBUS;
    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        accountBUS = new AccountBUS();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCategoryIDConfig8 = new javax.swing.JLabel();
        lblCategoryIDConfig9 = new javax.swing.JLabel();
        passwordTxt = new view.custom.passwordField();
        usernameTxt = new view.custom.textField();
        button5 = new view.custom.Button();

        setBackground(new java.awt.Color(255, 255, 255));

        lblCategoryIDConfig8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCategoryIDConfig8.setText("Tên đăng nhập:");

        lblCategoryIDConfig9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCategoryIDConfig9.setText("Mật khẩu:");

        passwordTxt.setLabelText("Mật khẩu");

        usernameTxt.setLabelText("Tên đăng nhập");

        button5.setBackground(new java.awt.Color(204, 204, 255));
        button5.setBorder(null);
        button5.setText("Đăng nhập");
        button5.setToolTipText("");
        button5.setBorderColor(new java.awt.Color(0, 0, 0));
        button5.setColor(new java.awt.Color(204, 204, 255));
        button5.setColorClick(new java.awt.Color(240, 235, 235));
        button5.setColorOver(new java.awt.Color(255, 255, 255));
        button5.setFocusPainted(false);
        button5.setRadius(20);
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCategoryIDConfig8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCategoryIDConfig9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoryIDConfig8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoryIDConfig9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        String username = usernameTxt.getText();
        String password = passwordTxt.getText();
        if(username.isBlank()||password.isBlank()){
            JOptionPane.showConfirmDialog(passwordTxt, "Vui lòng không để trống thông tin");
            return;
        }
        System.out.println(password);
        Account account = accountBUS.login(username, password);
        if(account==null){
            JOptionPane.showMessageDialog(this, "Tên đăng nhập hoặc mật khẩu không đúng");
            return;
        }
        if(!account.isActived()){
            JOptionPane.showMessageDialog(this, "Tài khoản chưa được kích hoạt bởi quản trị viên");
            return;
        }
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.dispose();
        try {
            new MainLayout(account).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.custom.Button button5;
    private javax.swing.JLabel lblCategoryIDConfig8;
    private javax.swing.JLabel lblCategoryIDConfig9;
    private view.custom.passwordField passwordTxt;
    private view.custom.textField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
