/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.Layout;

import controllers.AccountBUS;
import controllers.OwnerBUS;
import java.util.Date;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import models.Account;
import models.DriverLicense;
import models.Owner;
import view.custom.customDialog;

/**
 *
 * @author Son
 */
public class OwnerGUI extends javax.swing.JPanel {
    private OwnerBUS ownerBUS;
    private Owner selectedOwner;
    private Account account;
    private AccountBUS accountBUS;
    /**
     * Creates new form OwnerGUI
     */
    public OwnerGUI(Account account) {
        initComponents();
        ownerBUS = new OwnerBUS();
        accountBUS = new AccountBUS();
        this.account = account;
        SwingUtilities.invokeLater(() -> {
            parentFrame = (MainLayout) SwingUtilities.getWindowAncestor(this);
        });
        driverInfo = new customDialog(parentFrame);
        driverInfo.setDialogContent(licensePanel);
        setOwnersData();
    }
    public void setOwnerDetail(Owner selectedOwner){
        refresh();
        if(selectedOwner!=null){
            nameTxt.setText(selectedOwner.getFullName());
            cmndTxt.setText(selectedOwner.getCmnd());
            if(selectedOwner.getGender().equals("Nam"))
                maleOption.setSelected(true);
            else femaleOption.setSelected(true);
            addressTxt.setText(selectedOwner.getAddress());
            phoneTxt.setText(selectedOwner.getPhoneNumber());
            birthdateField.setDate(selectedOwner.getBirthday());
        }
        else {
            JOptionPane.showMessageDialog(parentFrame, "Có lỗi xảy ra, tiến hành tải lại trang...");
            setOwnersData();
        }
    }
    public void setOwnersData(){
        List<Owner> ownerList = ownerBUS.getAll();
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        for(Owner owner:ownerList){
            Object row[] = new Object[]{owner.getCmnd(),owner.getFullName()};
            model.addRow(row);
        }
    }
    public void updateDriverLicense(){
        String licenseId = this.licenseId.getText();
        String licenseClass = this.licenseClass.getText();
        String licenseAddress = this.licenseAddress.getText();
        Date licenseDate = this.licenseDate.getDate();
        if(licenseId==null||licenseClass==null||licenseAddress==null){
            JOptionPane.showMessageDialog(contentPanel2, "Không được để trống thông tin");
            return;
        }
        if(licenseDate.after(new Date())){
            JOptionPane.showMessageDialog(contentPanel2, "Ngày sinh không hợp lệ");
            return;
        }
        DriverLicense driverLicense = new DriverLicense(licenseId, licenseClass, licenseDate, licenseAddress);
        if(ownerBUS.saveDriverLicense(selectedOwner, driverLicense)){
            JOptionPane.showMessageDialog(contentPanel2, "Cập nhật thành công");
            driverInfo.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(contentPanel2, "ID của giấy phép không được trùng với người khác!");
        }
        
    }
    
    public boolean validateField(){
        String name = nameTxt.getText();
        String cmnd = cmndTxt.getText();
        String gender = genderOption.getSelection()==null?null:maleOption.isSelected()?"Nam":"Nữ";
        String address = addressTxt.getText();
        String phone = phoneTxt.getText();
        String phoneRegex = "^(0[0-9]{9}|\\+84[0-9]{9})$";
        String cmndRegex = "\\d{12}";
        Date birthday = birthdateField.getDate();
        if(name.isBlank() || cmnd.isBlank()||gender==null||address.isBlank()||phone.isBlank()){
            JOptionPane.showMessageDialog(contentPanel2, "Không được để trống thông tin");
            return false;
        }
        if(birthday.after(new Date())){
            JOptionPane.showMessageDialog(contentPanel2, "Ngày sinh không hợp lệ");
            return false;
        }
        if(!Pattern.compile(phoneRegex).matcher(phone).matches()){
            JOptionPane.showMessageDialog(this, "Định dạng số điện thoại 0xxx-xxx-xxx hoặc +84-xxx-xxx-xxx");
            return false;
        }
        if(!Pattern.compile(cmndRegex).matcher(cmnd).matches()){
            JOptionPane.showMessageDialog(this, "Định dạng số cmnd là 12 số");
            return false;
        }
        return true;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderOption = new javax.swing.ButtonGroup();
        licensePanel = new javax.swing.JPanel();
        lblCategoryIDConfig6 = new javax.swing.JLabel();
        licenseAddress = new javax.swing.JTextField();
        lblCategoryIDConfig7 = new javax.swing.JLabel();
        licenseDate = new de.wannawork.jcalendar.JCalendarComboBox();
        lblCategoryIDConfig8 = new javax.swing.JLabel();
        licenseClass = new javax.swing.JTextField();
        lblCategoryIDConfig9 = new javax.swing.JLabel();
        licenseId = new javax.swing.JTextField();
        button9 = new view.custom.Button();
        button10 = new view.custom.Button();
        button11 = new view.custom.Button();
        lblCategoryIDConfig10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        contentPanel2 = new javax.swing.JPanel();
        roundPanel3 = new view.custom.RoundPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        searchTxt = new javax.swing.JTextField();
        button3 = new view.custom.Button();
        roundPanel4 = new view.custom.RoundPanel();
        jPanel3 = new javax.swing.JPanel();
        lblCategoryIDConfig = new javax.swing.JLabel();
        lblCategoryIDConfig1 = new javax.swing.JLabel();
        lblCategoryIDConfig2 = new javax.swing.JLabel();
        button4 = new view.custom.Button();
        button5 = new view.custom.Button();
        button6 = new view.custom.Button();
        button7 = new view.custom.Button();
        cmndTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        maleOption = new javax.swing.JRadioButton();
        femaleOption = new javax.swing.JRadioButton();
        lblCategoryIDConfig3 = new javax.swing.JLabel();
        addressTxt = new javax.swing.JTextField();
        lblCategoryIDConfig4 = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();
        birthdateField = new de.wannawork.jcalendar.JCalendarComboBox();
        lblCategoryIDConfig5 = new javax.swing.JLabel();
        button8 = new view.custom.Button();

        licensePanel.setBackground(new java.awt.Color(255, 255, 255));
        licensePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCategoryIDConfig6.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblCategoryIDConfig6.setText("Nơi cấp:");

        licenseAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseAddressActionPerformed(evt);
            }
        });

        lblCategoryIDConfig7.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblCategoryIDConfig7.setText("Ngày cấp:");

        licenseDate.setFocusable(false);
        licenseDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblCategoryIDConfig8.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblCategoryIDConfig8.setText("Hạng:");

        lblCategoryIDConfig9.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblCategoryIDConfig9.setText("Số id:");

        button9.setBackground(new java.awt.Color(204, 204, 255));
        button9.setBorder(null);
        button9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/wrench.png"))); // NOI18N
        button9.setText("Cập nhật");
        button9.setToolTipText("");
        button9.setBorderColor(new java.awt.Color(0, 0, 0));
        button9.setColor(new java.awt.Color(204, 204, 255));
        button9.setColorClick(new java.awt.Color(240, 235, 235));
        button9.setColorOver(new java.awt.Color(255, 255, 255));
        button9.setFocusPainted(false);
        button9.setRadius(20);
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });

        button10.setBackground(new java.awt.Color(204, 204, 255));
        button10.setBorder(null);
        button10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/plus.png"))); // NOI18N
        button10.setText("Thêm");
        button10.setToolTipText("");
        button10.setBorderColor(new java.awt.Color(0, 0, 0));
        button10.setColor(new java.awt.Color(204, 204, 255));
        button10.setColorClick(new java.awt.Color(240, 235, 235));
        button10.setColorOver(new java.awt.Color(255, 255, 255));
        button10.setFocusPainted(false);
        button10.setRadius(20);
        button10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button10ActionPerformed(evt);
            }
        });

        button11.setBackground(new java.awt.Color(204, 204, 255));
        button11.setBorder(null);
        button11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/refresh.png"))); // NOI18N
        button11.setText("Làm mới");
        button11.setToolTipText("");
        button11.setBorderColor(new java.awt.Color(0, 0, 0));
        button11.setColor(new java.awt.Color(204, 204, 255));
        button11.setColorClick(new java.awt.Color(240, 235, 235));
        button11.setColorOver(new java.awt.Color(255, 255, 255));
        button11.setFocusPainted(false);
        button11.setRadius(20);
        button11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button11ActionPerformed(evt);
            }
        });

        lblCategoryIDConfig10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCategoryIDConfig10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCategoryIDConfig10.setText("Thông tin giấy phép");

        jButton1.setForeground(new java.awt.Color(102, 153, 255));
        jButton1.setText("Quay lại");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout licensePanelLayout = new javax.swing.GroupLayout(licensePanel);
        licensePanel.setLayout(licensePanelLayout);
        licensePanelLayout.setHorizontalGroup(
            licensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, licensePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(licensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(licensePanelLayout.createSequentialGroup()
                        .addComponent(button10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button11, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, licensePanelLayout.createSequentialGroup()
                        .addComponent(lblCategoryIDConfig9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(licenseId))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, licensePanelLayout.createSequentialGroup()
                        .addComponent(lblCategoryIDConfig8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(licenseClass))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, licensePanelLayout.createSequentialGroup()
                        .addGroup(licensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCategoryIDConfig6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoryIDConfig7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(licensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(licenseAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(licenseDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(19, 19, 19))
            .addComponent(lblCategoryIDConfig10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        licensePanelLayout.setVerticalGroup(
            licensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, licensePanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblCategoryIDConfig10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(licensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoryIDConfig9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(licenseId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(licensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoryIDConfig8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(licenseClass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(licensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoryIDConfig6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(licenseAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(licensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(licenseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoryIDConfig7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(licensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(8, 8, 8))
        );

        setPreferredSize(new java.awt.Dimension(1266, 550));

        contentPanel2.setBackground(new java.awt.Color(51, 51, 51));
        contentPanel2.setPreferredSize(new java.awt.Dimension(1266, 550));
        contentPanel2.setVerifyInputWhenFocusTarget(false);

        roundPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CMND", "Tên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(1).setResizable(false);
        }

        button3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/search.png"))); // NOI18N
        button3.setText("Tìm kiếm");
        button3.setRadius(5);
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundPanel3Layout = new javax.swing.GroupLayout(roundPanel3);
        roundPanel3.setLayout(roundPanel3Layout);
        roundPanel3Layout.setHorizontalGroup(
            roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                    .addGroup(roundPanel3Layout.createSequentialGroup()
                        .addComponent(searchTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );
        roundPanel3Layout.setVerticalGroup(
            roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addContainerGap())
        );

        roundPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin"));

        lblCategoryIDConfig.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblCategoryIDConfig.setText("Tên:");

        lblCategoryIDConfig1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblCategoryIDConfig1.setText("CMND:");

        lblCategoryIDConfig2.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblCategoryIDConfig2.setText("Giới tính:");

        button4.setBackground(new java.awt.Color(204, 204, 255));
        button4.setBorder(null);
        button4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/plus.png"))); // NOI18N
        button4.setText("Thêm");
        button4.setToolTipText("");
        button4.setBorderColor(new java.awt.Color(0, 0, 0));
        button4.setColor(new java.awt.Color(204, 204, 255));
        button4.setColorClick(new java.awt.Color(240, 235, 235));
        button4.setColorOver(new java.awt.Color(255, 255, 255));
        button4.setFocusPainted(false);
        button4.setRadius(20);
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        button5.setBackground(new java.awt.Color(204, 204, 255));
        button5.setBorder(null);
        button5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/wrench.png"))); // NOI18N
        button5.setText("Cập nhật");
        button5.setToolTipText("");
        button5.setBorderColor(new java.awt.Color(0, 0, 0));
        button5.setColor(new java.awt.Color(204, 204, 255));
        button5.setColorClick(new java.awt.Color(240, 235, 235));
        button5.setColorOver(new java.awt.Color(255, 255, 255));
        button5.setFocusPainted(false);
        button5.setRadius(20);
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        button6.setBackground(new java.awt.Color(204, 204, 255));
        button6.setBorder(null);
        button6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/refresh.png"))); // NOI18N
        button6.setText("Làm mới");
        button6.setToolTipText("");
        button6.setBorderColor(new java.awt.Color(0, 0, 0));
        button6.setColor(new java.awt.Color(204, 204, 255));
        button6.setColorClick(new java.awt.Color(240, 235, 235));
        button6.setColorOver(new java.awt.Color(255, 255, 255));
        button6.setFocusPainted(false);
        button6.setRadius(20);
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        button7.setBackground(new java.awt.Color(204, 204, 255));
        button7.setBorder(null);
        button7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/remove.png"))); // NOI18N
        button7.setText("Xóa");
        button7.setToolTipText("");
        button7.setBorderColor(new java.awt.Color(0, 0, 0));
        button7.setColor(new java.awt.Color(204, 204, 255));
        button7.setColorClick(new java.awt.Color(240, 235, 235));
        button7.setColorOver(new java.awt.Color(255, 255, 255));
        button7.setFocusPainted(false);
        button7.setRadius(20);
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        genderOption.add(maleOption);
        maleOption.setText("Nam");

        genderOption.add(femaleOption);
        femaleOption.setText("Nữ");

        lblCategoryIDConfig3.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblCategoryIDConfig3.setText("Địa chỉ:");

        lblCategoryIDConfig4.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblCategoryIDConfig4.setText("Số điện thoại:");

        birthdateField.setFocusable(false);
        birthdateField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblCategoryIDConfig5.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblCategoryIDConfig5.setText("Ngày sinh:");

        button8.setBackground(new java.awt.Color(204, 204, 255));
        button8.setBorder(null);
        button8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/plus.png"))); // NOI18N
        button8.setText("Xem giấy phép");
        button8.setToolTipText("");
        button8.setBorderColor(new java.awt.Color(0, 0, 0));
        button8.setColor(new java.awt.Color(204, 204, 255));
        button8.setColorClick(new java.awt.Color(240, 235, 235));
        button8.setColorOver(new java.awt.Color(255, 255, 255));
        button8.setFocusPainted(false);
        button8.setRadius(20);
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblCategoryIDConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(nameTxt)
                        .addGap(6, 6, 6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblCategoryIDConfig1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(cmndTxt)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblCategoryIDConfig2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(maleOption)
                        .addGap(18, 18, 18)
                        .addComponent(femaleOption)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblCategoryIDConfig3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(addressTxt))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCategoryIDConfig4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoryIDConfig5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(birthdateField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(phoneTxt)))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoryIDConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoryIDConfig1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmndTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoryIDConfig2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maleOption)
                    .addComponent(femaleOption))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoryIDConfig3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoryIDConfig4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(birthdateField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoryIDConfig5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout roundPanel4Layout = new javax.swing.GroupLayout(roundPanel4);
        roundPanel4.setLayout(roundPanel4Layout);
        roundPanel4Layout.setHorizontalGroup(
            roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        roundPanel4Layout.setVerticalGroup(
            roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout contentPanel2Layout = new javax.swing.GroupLayout(contentPanel2);
        contentPanel2.setLayout(contentPanel2Layout);
        contentPanel2Layout.setHorizontalGroup(
            contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(roundPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        contentPanel2Layout.setVerticalGroup(
            contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roundPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        if (evt.getClickCount() == 2) {
            JTable target = (JTable) evt.getSource();
            int row = target.getSelectedRow();
            String cmnd = table.getValueAt(row, 0).toString();
            selectedOwner = ownerBUS.getByCmnd(cmnd);
            setOwnerDetail(selectedOwner);
        }
    }//GEN-LAST:event_tableMouseClicked

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        if(accountBUS.getById(account.getId()).getRole().getOwnerManager()!=2){
            JOptionPane.showMessageDialog(contentPanel2, "Bạn không có quyền thao tác");
            return;
        }
        try{
            if(!validateField())
                return;
            String name = nameTxt.getText();
            String cmnd = cmndTxt.getText();
            String gender = genderOption.getSelection()==null?null:maleOption.isSelected()?"Nam":"Nữ";
            String address = addressTxt.getText();
            String phone = phoneTxt.getText();
            Date birthday = birthdateField.getDate();
            Owner createOwner = new Owner(name, birthday, cmnd, address, phone, gender);
            if(ownerBUS.save(createOwner)){
                JOptionPane.showMessageDialog(contentPanel2, "Thêm thành công!!");
                refresh();
            }else{
                JOptionPane.showMessageDialog(contentPanel2, "Thêm thất bại!!Hãy chắc chắn CMND chưa đựọc sử dụng");
            }
            setOwnersData();
            
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_button4ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        if(selectedOwner==null){
            JOptionPane.showMessageDialog(contentPanel2, "Vui lòng chọn một đối tượng để xem!!");
            return;
        }
        
        DriverLicense driverLicense=selectedOwner.getDriverLicense();
        if(driverLicense!=null){
            licenseId.setText(driverLicense.getId());
            licenseClass.setText(driverLicense.getHang());
            licenseDate.setDate(driverLicense.getCreatedDate());
            licenseAddress.setText(driverLicense.getAddress());
        }else{
            licenseId.setText("");
            licenseClass.setText("");
            licenseAddress.setText("");
        }
        driverInfo.setVisible(true);
    }//GEN-LAST:event_button8ActionPerformed

    private void licenseAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licenseAddressActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        updateDriverLicense();
    }//GEN-LAST:event_button9ActionPerformed

    private void button10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button10ActionPerformed
        updateDriverLicense();
    }//GEN-LAST:event_button10ActionPerformed

    private void button11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button11ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        if(accountBUS.getById(account.getId()).getRole().getOwnerManager()!=2){
            JOptionPane.showMessageDialog(contentPanel2, "Bạn không có quyền thao tác");
            return;
        }
        try{
            if(!validateField())
                return;
            String name = nameTxt.getText();
            String cmnd = cmndTxt.getText();
            String gender = genderOption.getSelection()==null?null:maleOption.isSelected()?"Nam":"Nữ";
            String address = addressTxt.getText();
            String phone = phoneTxt.getText();
            Date birthday = birthdateField.getDate();
            selectedOwner.setFullName(name);
            selectedOwner.setAddress(address);
            selectedOwner.setBirthday(birthday);
            selectedOwner.setCmnd(cmnd);
            selectedOwner.setGender(gender);
            selectedOwner.setPhoneNumber(phone);
            if(ownerBUS.save(selectedOwner)){
                JOptionPane.showMessageDialog(contentPanel2, "Cập nhật thành công!!");
                refresh();
                selectedOwner=null;
            }else{
                JOptionPane.showMessageDialog(contentPanel2, "Thêm thất bại!!Hãy chắc chắn CMND chưa đựọc sử dụng");
            }
            setOwnersData();
            
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        selectedOwner=null;
        refresh();
    }//GEN-LAST:event_button6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        driverInfo.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        if(accountBUS.getById(account.getId()).getRole().getOwnerManager()!=2){
            JOptionPane.showMessageDialog(contentPanel2, "Bạn không có quyền thao tác");
            return;
        }
        if(selectedOwner!=null){
            if(ownerBUS.delete(selectedOwner)){
                JOptionPane.showMessageDialog(parentFrame, "Xóa thành công");
                
            }else {
                JOptionPane.showMessageDialog(parentFrame, "Có lỗi xảy ra!! Tiến hành tải lại trang...");
            }
            refresh();
            setOwnersData();
        }else {
            JOptionPane.showMessageDialog(parentFrame, "Vui lòng chọn một đối tượng để thao tác");
        }
    }//GEN-LAST:event_button7ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        String cmnd = searchTxt.getText();
        List<Owner>ownerList = ownerBUS.getByCmndKeyword(cmnd);
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        for(Owner owner:ownerList){
            Object row[] = new Object[]{owner.getCmnd(),owner.getFullName()};
            model.addRow(row);
        }
        
    }//GEN-LAST:event_button3ActionPerformed
    public void refresh(){
        nameTxt.setText("");
        cmndTxt.setText("");
        genderOption.clearSelection();
        addressTxt.setText("");
        phoneTxt.setText("");
    }
    

    private MainLayout parentFrame;
    private customDialog driverInfo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTxt;
    private de.wannawork.jcalendar.JCalendarComboBox birthdateField;
    private view.custom.Button button10;
    private view.custom.Button button11;
    private view.custom.Button button3;
    private view.custom.Button button4;
    private view.custom.Button button5;
    private view.custom.Button button6;
    private view.custom.Button button7;
    private view.custom.Button button8;
    private view.custom.Button button9;
    private javax.swing.JTextField cmndTxt;
    private javax.swing.JPanel contentPanel2;
    private javax.swing.JRadioButton femaleOption;
    private javax.swing.ButtonGroup genderOption;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCategoryIDConfig;
    private javax.swing.JLabel lblCategoryIDConfig1;
    private javax.swing.JLabel lblCategoryIDConfig10;
    private javax.swing.JLabel lblCategoryIDConfig2;
    private javax.swing.JLabel lblCategoryIDConfig3;
    private javax.swing.JLabel lblCategoryIDConfig4;
    private javax.swing.JLabel lblCategoryIDConfig5;
    private javax.swing.JLabel lblCategoryIDConfig6;
    private javax.swing.JLabel lblCategoryIDConfig7;
    private javax.swing.JLabel lblCategoryIDConfig8;
    private javax.swing.JLabel lblCategoryIDConfig9;
    private javax.swing.JTextField licenseAddress;
    private javax.swing.JTextField licenseClass;
    private de.wannawork.jcalendar.JCalendarComboBox licenseDate;
    private javax.swing.JTextField licenseId;
    private javax.swing.JPanel licensePanel;
    private javax.swing.JRadioButton maleOption;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField phoneTxt;
    private view.custom.RoundPanel roundPanel3;
    private view.custom.RoundPanel roundPanel4;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
