/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.Layout;

import controllers.AccountBUS;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import models.Account;
import models.Role;

/**
 *
 * @author Son
 */
public class RegisterForm extends javax.swing.JPanel {
    private final AccountBUS accountBUS;
    /**
     * Creates new form LoginForm
     */
    public RegisterForm() {
        initComponents();
        accountBUS = new AccountBUS();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderOption = new javax.swing.ButtonGroup();
        lblCategoryIDConfig8 = new javax.swing.JLabel();
        passwordTxt = new view.custom.passwordField();
        usernameTxt = new view.custom.textField();
        registerBtn = new view.custom.Button();
        lblCategoryIDConfig10 = new javax.swing.JLabel();
        lblCategoryIDConfig11 = new javax.swing.JLabel();
        emailTxt = new view.custom.textField();
        lblCategoryIDConfig12 = new javax.swing.JLabel();
        phoneTxt = new view.custom.textField();
        lblCategoryIDConfig13 = new javax.swing.JLabel();
        maleOption = new javax.swing.JRadioButton();
        femaleOption = new javax.swing.JRadioButton();
        lblCategoryIDConfig14 = new javax.swing.JLabel();
        birthdateField = new de.wannawork.jcalendar.JCalendarComboBox();
        lblCategoryIDConfig15 = new javax.swing.JLabel();
        nameTxt = new view.custom.textField();

        setBackground(new java.awt.Color(255, 255, 255));

        lblCategoryIDConfig8.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lblCategoryIDConfig8.setText("Tên đăng nhập:");

        passwordTxt.setLabelText("Mật khẩu");

        usernameTxt.setLabelText("Tên đăng nhập");

        registerBtn.setBackground(new java.awt.Color(204, 204, 255));
        registerBtn.setBorder(null);
        registerBtn.setText("Đăng ký");
        registerBtn.setToolTipText("");
        registerBtn.setBorderColor(new java.awt.Color(0, 0, 0));
        registerBtn.setColor(new java.awt.Color(204, 204, 255));
        registerBtn.setColorClick(new java.awt.Color(240, 235, 235));
        registerBtn.setColorOver(new java.awt.Color(255, 255, 255));
        registerBtn.setFocusPainted(false);
        registerBtn.setRadius(20);
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        lblCategoryIDConfig10.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lblCategoryIDConfig10.setText("Mật khẩu:");

        lblCategoryIDConfig11.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lblCategoryIDConfig11.setText("Email:");

        emailTxt.setLabelText("Email");

        lblCategoryIDConfig12.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lblCategoryIDConfig12.setText("Số điện thoại:");

        phoneTxt.setLabelText("số điện thoại");

        lblCategoryIDConfig13.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lblCategoryIDConfig13.setText("Giới tính:");

        genderOption.add(maleOption);
        maleOption.setText("Nam");

        genderOption.add(femaleOption);
        femaleOption.setText("Nữ");

        lblCategoryIDConfig14.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lblCategoryIDConfig14.setText("Ngày sinh:");

        birthdateField.setFocusable(false);
        birthdateField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblCategoryIDConfig15.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lblCategoryIDConfig15.setText("Họ và tên:");

        nameTxt.setLabelText("Họ và tên");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCategoryIDConfig15, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCategoryIDConfig11, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCategoryIDConfig8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoryIDConfig10, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCategoryIDConfig12, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCategoryIDConfig13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(maleOption)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(femaleOption)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblCategoryIDConfig14, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(birthdateField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoryIDConfig8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoryIDConfig10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoryIDConfig11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoryIDConfig12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCategoryIDConfig13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(maleOption)
                        .addComponent(femaleOption)
                        .addComponent(lblCategoryIDConfig14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(birthdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoryIDConfig15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        String name = nameTxt.getText();
        String username = usernameTxt.getText();
        String email = emailTxt.getText();
        String password = passwordTxt.getText();
        String gender = genderOption.getSelection()==null?null:maleOption.isSelected()?"Nam":"Nữ";
        Date birthDate = birthdateField.getDate();
        String phone = phoneTxt.getText();
        String phoneRegex = "^(0[0-9]{9}|\\+84[0-9]{9})$";
        Pattern pattern = Pattern.compile(phoneRegex);
        Matcher matcher = pattern.matcher(phone);
        if(name.isBlank()||username.isBlank()||password.isBlank()||gender==null||phone.isBlank()){
            JOptionPane.showMessageDialog(this, "Vui lòng không để trống thông tin");
            return;
        }
        if(birthDate.after(new Date())){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng ngày sinh");
            return;
        }
        if(!matcher.matches()){
            JOptionPane.showMessageDialog(this, "Định dạng số điện thoại 0xxx-xxx-xxx hoặc +84-xxx-xxx-xxx");
            return;
        }
        Role role = new Role(0,0,0,0);
        Account account = new Account(name,username, password, role, email, gender, phone, birthDate);
        if(accountBUS.save(account)){
            JOptionPane.showMessageDialog(this, "Đăng ký thành công!!tài khoản chưa được kích hoạt, hãy thông báo với quản trị viên để được kích hoạt");
            reLogin();
        }else {
            JOptionPane.showConfirmDialog(this, "Có lỗi xảy ra!! Vui lòng thử lại");
        }
        
    }//GEN-LAST:event_registerBtnActionPerformed
    public void reLogin(){
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.dispose();
        new StartGUI().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.wannawork.jcalendar.JCalendarComboBox birthdateField;
    private view.custom.textField emailTxt;
    private javax.swing.JRadioButton femaleOption;
    private javax.swing.ButtonGroup genderOption;
    private javax.swing.JLabel lblCategoryIDConfig10;
    private javax.swing.JLabel lblCategoryIDConfig11;
    private javax.swing.JLabel lblCategoryIDConfig12;
    private javax.swing.JLabel lblCategoryIDConfig13;
    private javax.swing.JLabel lblCategoryIDConfig14;
    private javax.swing.JLabel lblCategoryIDConfig15;
    private javax.swing.JLabel lblCategoryIDConfig8;
    private javax.swing.JRadioButton maleOption;
    private view.custom.textField nameTxt;
    private view.custom.passwordField passwordTxt;
    private view.custom.textField phoneTxt;
    private view.custom.Button registerBtn;
    private view.custom.textField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
