/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.Layout;

import controllers.AccountBUS;
import controllers.RoleBUS;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import models.Account;
import models.Role;
import org.bson.types.ObjectId;

/**
 *
 * @author Son
 */
public class RoleGUI extends javax.swing.JPanel {
    private final RoleBUS roleBUS;
    private final AccountBUS accountBUS;
    private Role selectedRole;
    private Account account;

    /**
     * Creates new form OwnerGUI
     */
    public RoleGUI(Account account) {
        initComponents();
        this.account = account;
        roleBUS = new RoleBUS();
        accountBUS = new AccountBUS();
        getRoleData();
    }
    public void getRoleData(){
        List<Role> roles = roleBUS.getAll();
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        int i=0;
        for(Role role: roles){
            Object row[] = new Object[]{++i,role.getRoleName(),role.getId()};
            model.addRow(row);
        }
    }
    public void getRoleDetail(Role role){
        if(role==null){
            JOptionPane.showMessageDialog(contentPanel2, "Vui lòng chọn một đối tượng để thao tác");
        }
        nameTxt.setText(role.getRoleName());
        ownerRole.setSelectedIndex(role.getOwnerManager());
        transportationRole.setSelectedIndex(role.getTransportationManager());
        transportationTypeRole.setSelectedIndex(role.getTransportationTypeManager());
        AccountRole.setSelectedIndex(role.getAccountManager());
    }

    public void refresh(){
        nameTxt.setText("");
        ownerRole.setSelectedIndex(0);
        transportationRole.setSelectedIndex(0);
        transportationTypeRole.setSelectedIndex(0);
        AccountRole.setSelectedIndex(0);
    }
    public boolean validateField(){
        if(nameTxt.getText().isBlank()){
            JOptionPane.showMessageDialog(contentPanel2, "Vui lòng không để trống thông tin");
            return false;
        }
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel2 = new javax.swing.JPanel();
        roundPanel3 = new view.custom.RoundPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        searchTxt = new javax.swing.JTextField();
        search = new view.custom.Button();
        lblCategoryIDConfig8 = new javax.swing.JLabel();
        transportationTypeRole = new javax.swing.JComboBox<>();
        lblCategoryIDConfig6 = new javax.swing.JLabel();
        AccountRole = new javax.swing.JComboBox<>();
        lblCategoryIDConfig7 = new javax.swing.JLabel();
        transportationRole = new javax.swing.JComboBox<>();
        lblCategoryIDConfig5 = new javax.swing.JLabel();
        lblCategoryIDConfig = new javax.swing.JLabel();
        ownerRole = new javax.swing.JComboBox<>();
        lblCategoryIDConfig3 = new javax.swing.JLabel();
        nameTxt = new view.custom.textField();
        lblCategoryIDConfig4 = new javax.swing.JLabel();
        button4 = new view.custom.Button();
        button5 = new view.custom.Button();
        button6 = new view.custom.Button();
        button7 = new view.custom.Button();

        setPreferredSize(new java.awt.Dimension(1266, 550));

        contentPanel2.setBackground(new java.awt.Color(51, 51, 51));
        contentPanel2.setPreferredSize(new java.awt.Dimension(1266, 550));
        contentPanel2.setVerifyInputWhenFocusTarget(false);

        roundPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Vai trò", "id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setPreferredWidth(10);
            table.getColumnModel().getColumn(2).setMinWidth(0);
            table.getColumnModel().getColumn(2).setPreferredWidth(0);
            table.getColumnModel().getColumn(2).setMaxWidth(0);
        }

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/search.png"))); // NOI18N
        search.setText("Tìm kiếm");
        search.setRadius(5);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundPanel3Layout = new javax.swing.GroupLayout(roundPanel3);
        roundPanel3.setLayout(roundPanel3Layout);
        roundPanel3Layout.setHorizontalGroup(
            roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(roundPanel3Layout.createSequentialGroup()
                        .addComponent(searchTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        roundPanel3Layout.setVerticalGroup(
            roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblCategoryIDConfig8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCategoryIDConfig8.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoryIDConfig8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCategoryIDConfig8.setText("Phân quyền");

        transportationTypeRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vô hiệu", "Chỉ xem", "Chỉnh sửa" }));

        lblCategoryIDConfig6.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblCategoryIDConfig6.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoryIDConfig6.setText("Dòng xe:");

        AccountRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vô hiệu", "Chỉ xem", "Chỉnh sửa" }));

        lblCategoryIDConfig7.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblCategoryIDConfig7.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoryIDConfig7.setText("Tài khoản:");

        transportationRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vô hiệu", "Chỉ xem", "Chỉnh sửa" }));

        lblCategoryIDConfig5.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblCategoryIDConfig5.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoryIDConfig5.setText("Xe:");

        lblCategoryIDConfig.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblCategoryIDConfig.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoryIDConfig.setText("Quản lý:");

        ownerRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vô hiệu", "Chỉ xem", "Chỉnh sửa" }));

        lblCategoryIDConfig3.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblCategoryIDConfig3.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoryIDConfig3.setText("Vai trò:");

        nameTxt.setBackground(new java.awt.Color(51, 51, 51));
        nameTxt.setForeground(new java.awt.Color(255, 255, 255));
        nameTxt.setLabelText("Tên vai trò");

        lblCategoryIDConfig4.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblCategoryIDConfig4.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoryIDConfig4.setText("Chủ sở hữu:");

        button4.setBackground(new java.awt.Color(204, 204, 255));
        button4.setBorder(null);
        button4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/plus.png"))); // NOI18N
        button4.setText("Thêm");
        button4.setToolTipText("");
        button4.setBorderColor(new java.awt.Color(0, 0, 0));
        button4.setColor(new java.awt.Color(204, 204, 255));
        button4.setColorClick(new java.awt.Color(240, 235, 235));
        button4.setColorOver(new java.awt.Color(255, 255, 255));
        button4.setFocusPainted(false);
        button4.setRadius(20);
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        button5.setBackground(new java.awt.Color(204, 204, 255));
        button5.setBorder(null);
        button5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/wrench.png"))); // NOI18N
        button5.setText("Cập nhật");
        button5.setToolTipText("");
        button5.setBorderColor(new java.awt.Color(0, 0, 0));
        button5.setColor(new java.awt.Color(204, 204, 255));
        button5.setColorClick(new java.awt.Color(240, 235, 235));
        button5.setColorOver(new java.awt.Color(255, 255, 255));
        button5.setFocusPainted(false);
        button5.setRadius(20);
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        button6.setBackground(new java.awt.Color(204, 204, 255));
        button6.setBorder(null);
        button6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/refresh.png"))); // NOI18N
        button6.setText("Làm mới");
        button6.setToolTipText("");
        button6.setBorderColor(new java.awt.Color(0, 0, 0));
        button6.setColor(new java.awt.Color(204, 204, 255));
        button6.setColorClick(new java.awt.Color(240, 235, 235));
        button6.setColorOver(new java.awt.Color(255, 255, 255));
        button6.setFocusPainted(false);
        button6.setRadius(20);
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        button7.setBackground(new java.awt.Color(204, 204, 255));
        button7.setBorder(null);
        button7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/remove.png"))); // NOI18N
        button7.setText("Xóa");
        button7.setToolTipText("");
        button7.setBorderColor(new java.awt.Color(0, 0, 0));
        button7.setColor(new java.awt.Color(204, 204, 255));
        button7.setColorClick(new java.awt.Color(240, 235, 235));
        button7.setColorOver(new java.awt.Color(255, 255, 255));
        button7.setFocusPainted(false);
        button7.setRadius(20);
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentPanel2Layout = new javax.swing.GroupLayout(contentPanel2);
        contentPanel2.setLayout(contentPanel2Layout);
        contentPanel2Layout.setHorizontalGroup(
            contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(roundPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addGroup(contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCategoryIDConfig8, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanel2Layout.createSequentialGroup()
                                    .addGroup(contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(contentPanel2Layout.createSequentialGroup()
                                            .addGap(24, 24, 24)
                                            .addComponent(lblCategoryIDConfig4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ownerRole, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanel2Layout.createSequentialGroup()
                                            .addComponent(lblCategoryIDConfig5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(transportationRole, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(53, 53, 53)
                                    .addGroup(contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(contentPanel2Layout.createSequentialGroup()
                                            .addComponent(lblCategoryIDConfig7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(AccountRole, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(contentPanel2Layout.createSequentialGroup()
                                            .addComponent(lblCategoryIDConfig6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(transportationTypeRole, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanel2Layout.createSequentialGroup()
                                    .addComponent(lblCategoryIDConfig3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblCategoryIDConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(contentPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        contentPanel2Layout.setVerticalGroup(
            contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanel2Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contentPanel2Layout.createSequentialGroup()
                        .addComponent(lblCategoryIDConfig8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCategoryIDConfig3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblCategoryIDConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCategoryIDConfig6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ownerRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transportationTypeRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoryIDConfig4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCategoryIDConfig5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoryIDConfig7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transportationRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AccountRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        if (evt.getClickCount() == 2) {
            JTable target = (JTable) evt.getSource();
            int row = target.getSelectedRow();
            String idString = table.getValueAt(row, 2).toString();
            ObjectId id = new ObjectId(idString);
            selectedRole = roleBUS.getById(id);
            getRoleDetail(selectedRole);
        }
    }//GEN-LAST:event_tableMouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        String keyword = searchTxt.getText();
        List<Role> roles = roleBUS.getByNameKeyword(keyword);
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        int i=0;
        for(Role role: roles){
            Object row[] = new Object[]{++i,role.getRoleName(),role.getId()};
            model.addRow(row);
        }
    }//GEN-LAST:event_searchActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        if(accountBUS.getById(account.getId()).getRole().getAccountManager()!=2){
            JOptionPane.showMessageDialog(contentPanel2, "Bạn không có quyền thao tác");
            return;
        }
        try{
            String name = nameTxt.getText();
            if(validateField())
                return;
            Role createRole = new Role(name,ownerRole.getSelectedIndex(),transportationRole.getSelectedIndex(),transportationTypeRole.getSelectedIndex(),AccountRole.getSelectedIndex());
            if(roleBUS.save(createRole)){
                JOptionPane.showMessageDialog(contentPanel2, "Thêm thành công");
            }
        }catch(Exception e){

        }
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        if(accountBUS.getById(account.getId()).getRole().getAccountManager()!=2){
            JOptionPane.showMessageDialog(contentPanel2, "Bạn không có quyền thao tác");
            return;
        }
        if(selectedRole==null){
            JOptionPane.showMessageDialog(contentPanel2, "Vui lòng chọn một đối tượng thể thao tác");
            return;
        }
        int ownerRole = this.ownerRole.getSelectedIndex();
        int transportationRole = this.transportationRole.getSelectedIndex();
        int transportationTypeRole = this.transportationTypeRole.getSelectedIndex();
        int accountRole = AccountRole.getSelectedIndex();
        selectedRole.setOwnerManager(ownerRole);
        selectedRole.setTransportationManager(transportationRole);
        selectedRole.setTransportationTypeManager(transportationTypeRole);
        selectedRole.setAccountManager(accountRole);
        if(roleBUS.save(selectedRole)){
            JOptionPane.showMessageDialog(contentPanel2, "Cập nhật thành công!");
            refresh();
            selectedRole=null;
            getRoleData();
        }else {
            JOptionPane.showMessageDialog(contentPanel2, "Có lỗi xảy ra");
        }
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
                if(selectedRole!=null){
                    selectedRole = roleBUS.getById(selectedRole.getId());
                    getRoleDetail(selectedRole);
                }
                else
                JOptionPane.showMessageDialog(contentPanel2, "Vui lòng chọn một đối tượng để thao táo");
    }//GEN-LAST:event_button6ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        if(accountBUS.getById(account.getId()).getRole().getOwnerManager()!=2){
            JOptionPane.showMessageDialog(contentPanel2, "Bạn không có quyền thao tác");
            return;
        }
        if(selectedRole!=null){
            if(roleBUS.delete(selectedRole)){
                JOptionPane.showMessageDialog(contentPanel2, "Xóa thành công");
                refresh();
            }else {
                JOptionPane.showMessageDialog(contentPanel2, "Vẫn còn dữ liệu tài khoản thuộc vai trò này!! không thể xóa");
            }
            getRoleData();
        }else {
            JOptionPane.showMessageDialog(contentPanel2, "Vui lòng chọn một đối tượng để thao tác");
        }
    }//GEN-LAST:event_button7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AccountRole;
    private view.custom.Button button4;
    private view.custom.Button button5;
    private view.custom.Button button6;
    private view.custom.Button button7;
    private javax.swing.JPanel contentPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCategoryIDConfig;
    private javax.swing.JLabel lblCategoryIDConfig3;
    private javax.swing.JLabel lblCategoryIDConfig4;
    private javax.swing.JLabel lblCategoryIDConfig5;
    private javax.swing.JLabel lblCategoryIDConfig6;
    private javax.swing.JLabel lblCategoryIDConfig7;
    private javax.swing.JLabel lblCategoryIDConfig8;
    private view.custom.textField nameTxt;
    private javax.swing.JComboBox<String> ownerRole;
    private view.custom.RoundPanel roundPanel3;
    private view.custom.Button search;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JTable table;
    private javax.swing.JComboBox<String> transportationRole;
    private javax.swing.JComboBox<String> transportationTypeRole;
    // End of variables declaration//GEN-END:variables
}
