/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.Layout;

import controllers.AccountBUS;
import controllers.TransportationTypeBUS;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import models.Account;
import models.TransportationType;
import org.bson.types.ObjectId;

/**
 *
 * @author Son
 */
public class TransportationTypeGUI extends javax.swing.JPanel {
    private final TransportationTypeBUS transportationTypeBUS;
    private TransportationType selectedTransportationType;
    private Account account;
    private AccountBUS accountBUS;    
    /**
     * Creates new form OwnerGUI
     */
    public TransportationTypeGUI(Account account) {
        initComponents();
        accountBUS = new AccountBUS();
        this.account = account;
        transportationTypeBUS = new TransportationTypeBUS();
        getTransportationTypeData();
    }
    public void getTransportationTypeData(){
        List<TransportationType> transportationTypes = transportationTypeBUS.getAll();
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        int i=0;
        for(TransportationType transportationType: transportationTypes){
            Object row[] = new Object[]{++i,transportationType.getName(),transportationType.getBrand(),transportationType.getType(),transportationType.getId()};
            model.addRow(row);
        }
    }
    public void getTransportationTypeDetail(){
        refresh();
        if(selectedTransportationType!=null){
            nameTxt.setText(selectedTransportationType.getName());
            brandTxt.setText(selectedTransportationType.getBrand());
            typeTxt.setText(selectedTransportationType.getType());
        }else {
            JOptionPane.showMessageDialog(contentPanel2, "Có lỗi xảy ra!!Tiến hành tải lại trang...");
            getTransportationTypeData();
        }
    }
    public void refresh(){
        nameTxt.setText("");
        brandTxt.setText("");
        typeTxt.setText("");
    }
    public boolean validateField(){
        if(nameTxt.getText().isBlank()||brandTxt.getText().isBlank()||typeTxt.getText().isBlank()){
            JOptionPane.showMessageDialog(contentPanel2, "Vui lòng không để trống thông tin");
            return false;
        }
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel2 = new javax.swing.JPanel();
        roundPanel3 = new view.custom.RoundPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        searchTxt = new javax.swing.JTextField();
        search = new view.custom.Button();
        roundPanel4 = new view.custom.RoundPanel();
        jPanel3 = new javax.swing.JPanel();
        lblCategoryIDConfig = new javax.swing.JLabel();
        lblCategoryIDConfig1 = new javax.swing.JLabel();
        lblCategoryIDConfig2 = new javax.swing.JLabel();
        button4 = new view.custom.Button();
        button5 = new view.custom.Button();
        button6 = new view.custom.Button();
        button7 = new view.custom.Button();
        typeTxt = new javax.swing.JTextField();
        brandTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1266, 550));

        contentPanel2.setBackground(new java.awt.Color(51, 51, 51));
        contentPanel2.setPreferredSize(new java.awt.Dimension(1266, 550));
        contentPanel2.setVerifyInputWhenFocusTarget(false);

        roundPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên dòng xe", "Tên hãng xe", "Loại xe", "id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setPreferredWidth(10);
            table.getColumnModel().getColumn(4).setMinWidth(0);
            table.getColumnModel().getColumn(4).setPreferredWidth(0);
            table.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/search.png"))); // NOI18N
        search.setText("Tìm kiếm");
        search.setRadius(5);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundPanel3Layout = new javax.swing.GroupLayout(roundPanel3);
        roundPanel3.setLayout(roundPanel3Layout);
        roundPanel3Layout.setHorizontalGroup(
            roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                    .addGroup(roundPanel3Layout.createSequentialGroup()
                        .addComponent(searchTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );
        roundPanel3Layout.setVerticalGroup(
            roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                .addContainerGap())
        );

        roundPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin"));

        lblCategoryIDConfig.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblCategoryIDConfig.setText("Tên dòng xe:");

        lblCategoryIDConfig1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblCategoryIDConfig1.setText("Tên hãng xe:");

        lblCategoryIDConfig2.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblCategoryIDConfig2.setText("Loại xe:");

        button4.setBackground(new java.awt.Color(204, 204, 255));
        button4.setBorder(null);
        button4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/plus.png"))); // NOI18N
        button4.setText("Thêm");
        button4.setToolTipText("");
        button4.setBorderColor(new java.awt.Color(0, 0, 0));
        button4.setColor(new java.awt.Color(204, 204, 255));
        button4.setColorClick(new java.awt.Color(240, 235, 235));
        button4.setColorOver(new java.awt.Color(255, 255, 255));
        button4.setFocusPainted(false);
        button4.setRadius(20);
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        button5.setBackground(new java.awt.Color(204, 204, 255));
        button5.setBorder(null);
        button5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/wrench.png"))); // NOI18N
        button5.setText("Cập nhật");
        button5.setToolTipText("");
        button5.setBorderColor(new java.awt.Color(0, 0, 0));
        button5.setColor(new java.awt.Color(204, 204, 255));
        button5.setColorClick(new java.awt.Color(240, 235, 235));
        button5.setColorOver(new java.awt.Color(255, 255, 255));
        button5.setFocusPainted(false);
        button5.setRadius(20);
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        button6.setBackground(new java.awt.Color(204, 204, 255));
        button6.setBorder(null);
        button6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/refresh.png"))); // NOI18N
        button6.setText("Làm mới");
        button6.setToolTipText("");
        button6.setBorderColor(new java.awt.Color(0, 0, 0));
        button6.setColor(new java.awt.Color(204, 204, 255));
        button6.setColorClick(new java.awt.Color(240, 235, 235));
        button6.setColorOver(new java.awt.Color(255, 255, 255));
        button6.setFocusPainted(false);
        button6.setRadius(20);
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        button7.setBackground(new java.awt.Color(204, 204, 255));
        button7.setBorder(null);
        button7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/remove.png"))); // NOI18N
        button7.setText("Xóa");
        button7.setToolTipText("");
        button7.setBorderColor(new java.awt.Color(0, 0, 0));
        button7.setColor(new java.awt.Color(204, 204, 255));
        button7.setColorClick(new java.awt.Color(240, 235, 235));
        button7.setColorOver(new java.awt.Color(255, 255, 255));
        button7.setFocusPainted(false);
        button7.setRadius(20);
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblCategoryIDConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(nameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblCategoryIDConfig1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(brandTxt)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblCategoryIDConfig2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(typeTxt)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoryIDConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoryIDConfig1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoryIDConfig2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout roundPanel4Layout = new javax.swing.GroupLayout(roundPanel4);
        roundPanel4.setLayout(roundPanel4Layout);
        roundPanel4Layout.setHorizontalGroup(
            roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        roundPanel4Layout.setVerticalGroup(
            roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout contentPanel2Layout = new javax.swing.GroupLayout(contentPanel2);
        contentPanel2.setLayout(contentPanel2Layout);
        contentPanel2Layout.setHorizontalGroup(
            contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(roundPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        contentPanel2Layout.setVerticalGroup(
            contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(contentPanel2Layout.createSequentialGroup()
                        .addComponent(roundPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        if (evt.getClickCount() == 2) {
            JTable target = (JTable) evt.getSource();
            int row = target.getSelectedRow();
            ObjectId id =(ObjectId) table.getValueAt(row, 4);
            selectedTransportationType = transportationTypeBUS.getById(id);
            getTransportationTypeDetail();
        }
    }//GEN-LAST:event_tableMouseClicked

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        if(selectedTransportationType!=null)
            getTransportationTypeDetail();
        else 
            JOptionPane.showMessageDialog(contentPanel2, "Vui lòng chọn một đối tượng để thao táo");
    }//GEN-LAST:event_button6ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        if(accountBUS.getById(account.getId()).getRole().getTransportationTypeManager()!=2){
            JOptionPane.showMessageDialog(contentPanel2, "Bạn không có quyền thao tác");
            return;
        }
        if(!validateField())
            return;
        String name = nameTxt.getText();
        String brand = brandTxt.getText();
        String type = typeTxt.getText();
        TransportationType createTransportationType = new TransportationType(name, brand, type);
        if(transportationTypeBUS.save(createTransportationType)){
            JOptionPane.showMessageDialog(contentPanel2, "Thêm thành công");
            refresh();
        }else{
            JOptionPane.showMessageDialog(contentPanel2, "Có lỗi xảy ra!!");
        }
        getTransportationTypeData();
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        if(accountBUS.getById(account.getId()).getRole().getTransportationTypeManager()!=2){
            JOptionPane.showMessageDialog(contentPanel2, "Bạn không có quyền thao tác");
            return;
        }
        if(selectedTransportationType==null){
            JOptionPane.showMessageDialog(contentPanel2, "Vui lòng chọn đối tượng thể thao tác");
            return;
        }
        if(!validateField())
            return;
        String name = nameTxt.getText();
        String brand = brandTxt.getText();
        String type = typeTxt.getText();
        selectedTransportationType.setName(name);
        selectedTransportationType.setBrand(brand);
        selectedTransportationType.setType(type);
        if(transportationTypeBUS.save(selectedTransportationType)){
            JOptionPane.showMessageDialog(contentPanel2, "Cập nhật thành công");
            refresh();
            selectedTransportationType=null;
        }else{
            JOptionPane.showMessageDialog(contentPanel2, "Có lỗi xảy ra!!");
        }
        getTransportationTypeData();
    }//GEN-LAST:event_button5ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        if(accountBUS.getById(account.getId()).getRole().getTransportationTypeManager()!=2){
            JOptionPane.showMessageDialog(contentPanel2, "Bạn không có quyền thao tác");
            return;
        }
        if(selectedTransportationType!=null){
            if(transportationTypeBUS.delete(selectedTransportationType)){
                JOptionPane.showMessageDialog(contentPanel2, "Xóa thành công");
                refresh();
            }
            else 
                JOptionPane.showMessageDialog(contentPanel2,"Vẫn còn dữ liệu xe thuộc dòng xe này!! Không thể xóa");
            getTransportationTypeData();
        }else {
            JOptionPane.showMessageDialog(contentPanel2, "Vui lòng chọn một đối tượng để thao tác");
        }
    }//GEN-LAST:event_button7ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        String keyword = searchTxt.getText();
        List<TransportationType> transportationTypes = transportationTypeBUS.getByNameKeyword(keyword);
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        int i=0;
        for(TransportationType transportationType: transportationTypes){
            Object row[] = new Object[]{++i,transportationType.getName(),transportationType.getBrand(),transportationType.getType(),transportationType.getId()};
            model.addRow(row);
        }
    }//GEN-LAST:event_searchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brandTxt;
    private view.custom.Button button4;
    private view.custom.Button button5;
    private view.custom.Button button6;
    private view.custom.Button button7;
    private javax.swing.JPanel contentPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCategoryIDConfig;
    private javax.swing.JLabel lblCategoryIDConfig1;
    private javax.swing.JLabel lblCategoryIDConfig2;
    private javax.swing.JTextField nameTxt;
    private view.custom.RoundPanel roundPanel3;
    private view.custom.RoundPanel roundPanel4;
    private view.custom.Button search;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JTable table;
    private javax.swing.JTextField typeTxt;
    // End of variables declaration//GEN-END:variables
}
